
modera_mjr_integration:
    resource: "@ModeraMjrIntegrationBundle/Controller/"
    type:     annotation
    prefix:   '%modera_mjr_integration.routes_prefix%'

modera_font_awesome_js:
    path:      /font-awesome.js
    defaults:  { _controller: ModeraMjrIntegrationBundle:Index:fontAwesomeJs }

modera_font_awesome_css:
    path:      /font-awesome.css
    defaults:  { _controller: ModeraMjrIntegrationBundle:Index:fontAwesomeCss }
