
modera_mjr_integration:
    type: annotation
    prefix: '%modera_mjr_integration.routes_prefix%'
    resource: '@ModeraMjrIntegrationBundle/Controller/'

modera_font_awesome_js:
    path: /font-awesome.js
    defaults:
        _controller: Modera\MjrIntegrationBundle\Controller\IndexController::fontAwesomeJsAction

modera_font_awesome_css:
    path: /font-awesome.css
    defaults:
        _controller: Modera\MjrIntegrationBundle\Controller\IndexController::fontAwesomeCssAction
